services:
  - type: web
    name: telemetrywatch
    env: docker
    dockerfilePath: ./docker/Dockerfile
    dockerContext: .
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        fromService:
          type: web
          name: telemetrywatch
          property: port
      - key: DATABASE_URL
        fromDatabase:
          name: telemetrywatch-db
          property: connectionString
      - key: DATABASE_MAX_CONNECTIONS
        value: 10
      - key: METRICS_ENABLED
        value: true

databases:
  - name: telemetrywatch-db
    databaseName: telemetrywatch
    user: telemetrywatch
    plan: free

